task:
  only_if: $CIRRUS_BRANCH != 'gh-pages'
  matrix:
    - name: build
      container:
        image: squidfunk/mkdocs-material:latest
      install_script: pip install --upgrade pymdown-extensions
      build_script: mkdocs build
    - name: lint
      container:
        image: node:latest
      install_script: npm install -g markdownlint-cli
      lint_script: markdownlint --config=.markdownlint.yml docs/

deploy_task:
  only_if: $CIRRUS_BRANCH == 'master'
  depends_on:
    - build
    - lint
  container:
    image: squidfunk/mkdocs-material:latest
  env:
    DEPLOY_TOKEN: ENCRYPTED[fbf2f9b7dc97cc3d960126b1540f19c36b96768c46b8eb99389e02b8c54080418d1fb90094dc2e3a36767df34acb5d5d]
  install_script: pip install --upgrade pymdown-extensions
  deploy_script: ./.ci/deploy.sh
