task:
  only_if: $CIRRUS_BRANCH != 'gh-pages'
  matrix:
    - name: build
      container:
        dockerfile: .ci/Dockerfile
      install_script: pip install --upgrade pymdown-extensions
      build_script: mkdocs build
      validate_script: liche --document-root=site --recursive site/
    - name: lint
      container:
        image: node:latest
      install_script: npm install -g markdownlint-cli
      lint_script: markdownlint --config=.markdownlint.yml docs/

spell-check_task:
  only_if: true
  use_compute_credits: false
  container:
    image: node:latest
  install_tool_script:
    # WARNING: DO NOT try to cache this, symlinks will not be created and task will fail
    - sudo npm install -g markdown-spellcheck@0.11.0
  script: mdspell '**/*.md' '!**/legal/*.md' --ignore-numbers --ignore-acronyms --report --en-us;

deploy_task:
  only_if: $CIRRUS_BRANCH == 'master'
  depends_on:
    - build
    - lint
  container:
    dockerfile: .ci/Dockerfile
  env:
    DEPLOY_TOKEN: ENCRYPTED[fbf2f9b7dc97cc3d960126b1540f19c36b96768c46b8eb99389e02b8c54080418d1fb90094dc2e3a36767df34acb5d5d]
  install_script: pip install --upgrade pymdown-extensions
  deploy_script: ./.ci/deploy.sh
