container:
  cpu: 1
  memory: 1G

env:
  MKDOCS_VERSION: 4.6.3

pipe:
  name: Build Site and Validate Links
  only_if: $CIRRUS_BRANCH != 'gh-pages'
  steps:
    - image: squidfunk/mkdocs-material:$MKDOCS_VERSION
      install_script: python3 -m pip install --upgrade -r requirements.txt
      build_script: mkdocs build
    - image: raviqqe/liche:latest
      validate_script: /liche --document-root=site --recursive site/

task:
  name: Markdown Lint
  only_if: $CIRRUS_BRANCH != 'gh-pages'
  container:
    image: node:latest
  install_script: npm install -g markdownlint-cli
  lint_script: markdownlint --config=.markdownlint.yml docs/

task:
  name: Spell Check
  only_if: $CIRRUS_BRANCH != 'gh-pages'
  container:
    image: node:latest
  install_tool_script:
    # WARNING: DO NOT try to cache this, symlinks will not be created and task will fail
    - npm install -g markdown-spellcheck@0.11.0
  script: mdspell '**/*.md' '!**/legal/*.md' --ignore-numbers --ignore-acronyms --report --en-us;

task:
  name: Deploy
  only_if: $CIRRUS_BRANCH == 'master'
  depends_on:
    - Build Site and Validate Links
    - Markdown Lint
    - Spell Check
  container:
    image: squidfunk/mkdocs-material:$MKDOCS_VERSION
  env:
    DEPLOY_TOKEN: ENCRYPTED[fbf2f9b7dc97cc3d960126b1540f19c36b96768c46b8eb99389e02b8c54080418d1fb90094dc2e3a36767df34acb5d5d]
  install_script: python3 -m pip install --upgrade -r requirements.txt
  deploy_script: ./.ci/deploy.sh
