container:
  image: squidfunk/mkdocs-material:latest
  image: node:latest
  image: python:latest
  cpu: 2

build_task:
  only_if: $CIRRUS_BRANCH != 'gh-pages' && $CIRRUS_BRANCH != 'master'
  install_script: pip install --upgrade pymdown-extensions
  build_script: mkdocs build

deploy_task:
  only_if: $CIRRUS_BRANCH == 'master'
  depends_on:
    - build
    - markdown_lint
    - markdown_linkcheck
  env:
    DEPLOY_TOKEN: ENCRYPTED[fbf2f9b7dc97cc3d960126b1540f19c36b96768c46b8eb99389e02b8c54080418d1fb90094dc2e3a36767df34acb5d5d]
  install_script: pip install pymdown-extensions
  deploy_script: ./.ci/deploy.sh

markdown_lint_task:
  install_script:
    - npm install -g remark-lint remark-cli
  script: 
    - echo ========  STARTING MARKDOWN LINTING TESTS  ========
    - find . -name \*.md -exec remark {} \;

markdown_linkcheck_task:
  install_script:
    - npm install -g markdown-link-check@3.7.2
  script:
    - echo ========  STARTING MARKDOWN LINK CHECK TESTS  ========
    - find . -name \*.md -exec markdown-link-check {} \;
